// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProvasEnem.Api.Data;

#nullable disable

namespace ProvasEnem.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240703105245_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProvasEnem.Core.Models.ExamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorNotebook")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Color Notebook");

                    b.Property<byte[]>("ContentPdf")
                        .IsRequired()
                        .HasColumnType("IMAGE")
                        .HasColumnName("PDF");

                    b.Property<DateTime>("ExamDate")
                        .HasMaxLength(20)
                        .HasColumnType("DATETIME2")
                        .HasColumnName("Exam Date");

                    b.HasKey("Id");

                    b.ToTable("Exams", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
